services:                                      
  frontend:                                      
    build:                                         
      context: .                                   
      dockerfile: Dockerfile                     
    ports: 
      - "4173:4173"                              
    container_name: launchdarkly_frontend        
    restart: always 